// dashboard/src/app/(dashboard)/marketplace/page.tsx
'use client'

import { Button } from '@/components/ui/button'
import { usePlugins } from '@/features/repos/hooks'
import { cn } from '@/lib/utils'

export default function MarketplacePage() {
  const { data: plugins, isLoading } = usePlugins()

  if (isLoading) {
    return (
      <div className="space-y-6">
        <h1 className="text-2xl font-bold tracking-tight">插件市场</h1>
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-px bg-border rounded-lg overflow-hidden">
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="h-48 bg-card animate-pulse" />
          ))}
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold tracking-tight">插件市场</h1>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-px bg-border rounded-lg overflow-hidden">
        {plugins?.map((plugin) => (
          <div key={plugin.id} className="bg-card p-5 flex flex-col">
            <div className="text-2xl mb-3">{plugin.icon}</div>
            <div className="text-sm font-semibold mb-1">{plugin.name}</div>
            <p className="text-xs text-muted-foreground leading-relaxed mb-3 flex-1">{plugin.description}</p>
            <div className="flex items-center justify-between">
              <span className="text-[11px] text-muted-foreground">
                {plugin.author === 'official' ? '官方' : '社区'}
                {plugin.price !== null && ` · $${plugin.price}/月`}
                {plugin.price === null && ' · 免费'}
              </span>
              <Button variant={plugin.installed ? 'outline' : 'default'} size="sm" className={cn('text-[11px] h-7', plugin.installed && 'border-green-500/30 text-green-500')}>
                {plugin.installed ? '已安装' : '安装'}
              </Button>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// frontend/apps/selfhost/pages/marketplace.vue
<script setup lang="ts">
import { useRepoList } from '@gwei/core/composables/useRepoList'

const { plugins, loading } = useRepoList()
</script>

<template>
  <div class="space-y-6">
    <h1 class="text-2xl font-bold tracking-tight">插件市场</h1>

    <!-- Skeleton loader -->
    <div
      v-if="loading"
      class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-px bg-border rounded-lg overflow-hidden"
    >
      <div v-for="i in 6" :key="i" class="h-48 bg-card animate-pulse" />
    </div>

    <!-- Plugin cards -->
    <div
      v-else
      class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-px bg-border rounded-lg overflow-hidden"
    >
      <div
        v-for="plugin in plugins"
        :key="plugin.id"
        class="bg-card p-5 flex flex-col"
      >
        <div class="text-2xl mb-3">{{ plugin.icon }}</div>
        <div class="text-sm font-semibold mb-1">{{ plugin.name }}</div>
        <p class="text-xs text-muted-foreground leading-relaxed mb-3 flex-1">
          {{ plugin.description }}
        </p>
        <div class="flex items-center justify-between">
          <span class="text-[11px] text-muted-foreground">
            {{ plugin.author === 'official' ? '官方' : '社区' }}
            <template v-if="plugin.price !== null"> · ${{ plugin.price }}/月</template>
            <template v-else> · 免费</template>
          </span>
          <Button
            :class="[
              'text-[11px] h-7 px-3',
              plugin.installed
                ? 'border border-green-500/30 text-green-500 bg-background shadow-sm hover:bg-green-500/10 hover:text-green-500'
                : '',
            ]"
          >
            {{ plugin.installed ? '已安装' : '安装' }}
          </Button>
        </div>
      </div>
    </div>
  </div>
</template>
