// dashboard/src/components/empty-state.tsx
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

interface EmptyStateProps {
  icon: string
  title: string
  description: string
  action?: { label: string; href: string }
  className?: string
}

export function EmptyState({ icon, title, description, action, className }: EmptyStateProps) {
  return (
    <div className={cn('flex flex-col items-center justify-center py-12 text-center', className)}>
      <div className="text-4xl mb-4">{icon}</div>
      <h3 className="text-lg font-semibold mb-2">{title}</h3>
      <p className="text-sm text-muted-foreground max-w-sm mb-6">{description}</p>
      {action && <Button asChild><Link href={action.href}>{action.label}</Link></Button>}
    </div>
  )
}

// frontend/packages/core/components/EmptyState.vue
<script setup lang="ts">
import { cn } from '../utils/cn'
import Button from './ui/Button.vue'

defineProps<{
  icon: string
  title: string
  description: string
  action?: { label: string; href: string }
}>()
</script>

<template>
  <div :class="cn('flex flex-col items-center justify-center py-12 text-center', $attrs.class as string | undefined)">
    <div class="text-4xl mb-4">{{ $props.icon }}</div>
    <h3 class="text-lg font-semibold mb-2">{{ $props.title }}</h3>
    <p class="text-sm text-muted-foreground max-w-sm mb-6">{{ $props.description }}</p>
    <Button v-if="$props.action" as="a" :href="$props.action.href">
      {{ $props.action.label }}
    </Button>
  </div>
</template>
